server:
  AppVersion: 1.0.0
  Port: 4000
  Mode: Development

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: postgres
  PostgresqlSslmode: false