server:
  AppVersion: 1.0.0
  Port: :4000
  Mode: Development

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: quest
  PostgresqlPassword: quest
  PostgresqlDbname: pg_dev
  PostgresqlSslmode: false